// <auto-generated />
using System;
using BlogManager_Tam.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogManager_Tam.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BlogManager_Tam.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BlogManager_Tam.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Tâm",
                            Content = "Bài viết giới thiệu các kiến thức nền tảng về ngôn ngữ C#.",
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "C# cơ bản",
                            ViewCount = 250
                        },
                        new
                        {
                            Id = 2,
                            Author = "Hải",
                            Content = "Bài viết hướng dẫn cách tổ chức một ứng dụng theo mô hình MVC.",
                            IsPublished = false,
                            PublishedAt = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "MVC nhập môn",
                            ViewCount = 150
                        },
                        new
                        {
                            Id = 3,
                            Author = "Hoàng",
                            Content = "Bài viết tổng quan về Entity Framework Core và cách thao tác dữ liệu.",
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "EF Core",
                            ViewCount = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
